apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: date-nginx
  template:
    metadata:
      labels:
        app: date-nginx
    spec:
      containers:
      - name: date-nginx
        image: guy:test
        ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: date-nginx-service
spec:
  type: LoadBalancer
  selector:
    app: date-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

